version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    build:
      context: pipeline
    hostname: jenkins
    restart: unless-stopped
    ports:
      - "8000:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jn-net

volumes:
  jenkins_home:

networks:
  jn-net:
