pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh '''
                   ./jenkins/build/build.sh mvn -B -DskipTest clean package
                   ./jenkins/build/script.sh 
                   '''
            }
        }
    }
}
